spring:
  application:
    name: his-tenant
  profiles:
    active: @spring.profiles.active@
  jackson:
    date-format: com.luna.framework.web.convert.AutoDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/**/*.xml


