logging:
  level:
    com.luna.tenant: DEBUG

server:
  port: 18030

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.0.98:8848
        namespace: luna
        group: DEV_GROUP
  datasource:
    name: luna-tenant
    url: jdbc:mysql://172.16.0.97:3306/his_tenant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: netin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 15
  redis:
    host: 172.16.0.98
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 5000
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

# 系统业务相关配置
tenant:
  # 是否开启跨域，如果使用网关则不需要开启
  cors-enabled: false

# 认证相关配置
auth:
  # 请求中token对应header的域名
  token-field: Authorization
  # token过期时长（毫秒）
  token-expire-milliseconds: 86400000
  # token长过期时长（毫秒）
  token-long-expire-milliseconds: 86400000
  # 刷新的token对应header的域名
  token-refresh-field: New-Token
  # token过期剩余间隔多少可以刷新
  token-refresh-interval-milliseconds: 600000
  # jwt rsa 私钥
  rsa-private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALBTbumRsw1oll2hYWKQ3FgrIAh51zZ9S4wfDlb3Pa_M8w1xCmjXU7AoimfWnZy3HxYKkWRPTCpfsKERj7PE5Tf6VNK1M9AZFmgeR1ZxfIdnnay6yg3jITrCFzMhbCzN5tjgA1XZMXIyBVA2wxHSbEyzo9boITYLkHbSn0lhHk2FAgMBAAECgYApUVOzHbYkVTau-Ar26tUHQAvAkLRyi0exrPFSRZtJ36-wnaV_zb1JkSZlkK_cMjjxlEZfiAlkAIpGI_RVfrTrViPNBaJTvWy5hXYLk0Y4Lg4qbBiU2me3A9tv7w7fTqjjrw6sUHNrILV82AuH2giEEAMNnZ0KvV2Sb-8jC9Z-AQJBAOf7KB01_PY31lgqelEAdgHYryg3HZ5IdtSsB2udsLbigMmPQwCDBwPc9OZwmov-pU7Aj8nHkgKkPKG4hE279YECQQDClReKhDHb3U2slOY9fmToxcykWBPxWrNMR5V9P68f1QMwTXF2e7c-N5m3kcNp9mVJ_05gIqhP7nKcOsDTR4IFAkEAsXzJ3j-WQVPLXT1yxFLT9umwadZxhM7wjBrqun213NdDrfM8UkHtthjyDvWMaRv1omFWIg3dOsQp15nzL_5lAQJAVAq1GjyylDXnYI0HTLQUvX0BQFJSesIkAuRAKtKgvuzv7aLlSLlykcrN971bW57ybJ16qocNj0h79AJkWlzeSQJAOzeJ87qQsVwyfZzvpQLqJ6v2lt2O5lpWiE9H4AM_d-O012uypn1tcB6Mirh8KEFSks7slLqdlt-TEZGlGXaI-w
  # jwt rsa 公钥
  rsa-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCwU27pkbMNaJZdoWFikNxYKyAIedc2fUuMHw5W9z2vzPMNcQpo11OwKIpn1p2ctx8WCpFkT0wqX7ChEY-zxOU3-lTStTPQGRZoHkdWcXyHZ52susoN4yE6whczIWwszebY4ANV2TFyMgVQNsMR0mxMs6PW6CE2C5B20p9JYR5NhQIDAQAB
